### PR TITLE
Bump Docker version

### PR DESCRIPTION
**Pull request by eirslett**
This will enable usage of multi-stage Dockerfiles.

### CODE REVIEW

**Comment by gtcno** [comment]
The validated docker versions are the same as for v1.8: 1.11.2 to 1.13.1 and 17.03.x

**Comment by gtcno** [comment]
This is the docker version on the kubernetes node. We should use the version that k8s is tested against

**Comment by Kyrremann** [comment]
Multi-stage dockerfile looked pretty nice, but agree with Giao, we should wait til k8s updates.

**Comment by davidsteinsland** [comment]
I don't think there's anything in the way of using a newer Docker version locally that supports multi-stage builds. The "multi-stage part" is not something that's included in the resulting image anyways.

**Comment by gtcno** [comment]
This inventory file is used to specify the docker version installed on the kubernetes worker nodes which runs the containers. Locally or in a build pipeline, feel free to run whatever version you fancy. :)

**Pull request closed without merging**
