### PR TITLE
Let naisible control election config for naisd

### PR DESCRIPTION
**Pull request by Kyrremann**
Two reasons:

1. We are having timing issues with Landscaper, meaning that it won't always deploy because of missing dependencies (read: namespace missing, or role missing)
2. It looks like Helm might not be the best place to define the namespace and role bindings, as it is supposed to be able to install the same chart to different namespaces without affecting each other. The preivous config would delete the elector namespace, if we deleted the naisd chart from one

### CODE REVIEW

**Comment by giacung** [comment]
I dont think this is a good idea at all. Now you have a hidden dependency from naisd to naisible.

**Comment by Kyrremann** [comment]
Don't we already have that with the `clusterrole` and `clusterrolebinding` `nais-developer` and where ever the `nais` `namespace` is made?

**Comment by gtcno** [comment]
The roles are to grant rbac access to the cluster

**Comment by gtcno** [comment]
This feature is very much coupled to naisd. And i feel it's warranted to have a look at stages in landscaper or possibly let naisd create the namespace and service account requiered to run the sidecar

**Comment by jhrv** [comment]
the nais namespace is not something naisd cares about, this is just for our own sake to group the platform resources. The roles and rolebindings is NAV-specific, and has nothing to do with naisd.

I agree that it could be naisd's responsibility to ensure that the resources required for leaderelection exists. This way, if anyone else uses naisd outside NAV, they don't have to run naisible (or similar) to make election work

**Comment by Kyrremann** [comment]
I'm thinking about closing and deleting this PR, as I'm having a hard time recreating the issue, and I do agree that Naisible is not the right place to have the code.

**Comment by jhrv** [comment]
You can recreate if you have a newly created cluster

**Comment by Kyrremann** [comment]
Solved with it own chart, that we depend on from naisd.

**Pull request closed without merging**
