### PR TITLE
enable auth with oidc

### PR DESCRIPTION
**Pull request by audunstrand**
enabling openid-connect.
@jhrv @giacung

### CODE REVIEW

**Comment by jhrv** [comment]
maybe extract the values into inventory and update readme?

**Comment by jhrv** [comment]
what happens with apiserver if these values are undefined? Should it be possible to exclude the extra apiserver settings if not using oidc or in this exact fashion? @knutjda

**Comment by knutjda** [comment]
If OpenId Connect is a requirement for Nais, it should embed its own provider like Dex or similar. Otherwise I think it should be feature toggled by variables in inventory.

**Comment by audunstrand** [comment]
No made it optinal. Empty will start api server, without oidc

**Pull request merged**
