### PR TITLE
etcd HA support 

### PR DESCRIPTION
**Pull request by jhrv**
Extracts etcd into separate and multiple machines (possible with single node too)
@knutjda @Muni10  @frodesundby @giacung  @audunstrand

### CODE REVIEW

**Comment by knutjda** [comment]
example-inventory-file and the examples in readme.md should be updated with the new [etcd] group. 
If the [etcd] group isn't defined in the inventory-file, I'll guess that the setup will fail. Is there any easy way of adding the hosts of the [masters] group to etcd then? Just to keep the inventory as small and easy as possible.

**Comment by jhrv** [comment]
If the etcd-group is not defined, then the apiserver will not be able start. Do you mean migrating existing master hosts to etcd with a running setup, or having the same hosts in both masters and etcd group?

**Comment by knutjda** [comment]
If the etcd-group is not defined, you probably want the master hosts to also run etcd. This way it is easier to start using naisible, and still be able to scale to more advanced setups. 
However, it might be too complicated to realize.

**Comment by jhrv** [comment]
to achieve this it should be possible to place the same host in both the masters and the etcd group. It might be possible to do this automagically, but I think this way it's more explicit

**Pull request merged**
