### PR TITLE
Added role and binding for leader election

### PR DESCRIPTION
**Pull request by Kyrremann**

### CODE REVIEW

**Comment by giacung** [comment]
Hmm. This should probably be in naisd repo?
Since the namespace, role and rolebindings are meaningless without the actual logic that injects the sidecar

**Comment by Kyrremann** [comment]
Do we have ansible/k8s config in that repo too?

**Comment by gtcno** [comment]
https://github.com/nais/naisd/tree/master/helm/naisd/templates

**Comment by Kyrremann** [comment]
Oh, didn't know. I'll move this tomorrow the.

**Pull request closed without merging**
